library verilog;
use verilog.vl_types.all;
entity cabac_enc_top is
    generic(
        CTX_ID_W        : integer := 8;
        COEFF_W         : integer := 16;
        MVD_W           : integer := 12;
        N_COEFF         : integer := 16
    );
    port(
        clk             : in     vl_logic;
        rst_n           : in     vl_logic;
        slice_init      : in     vl_logic;
        slice_type      : in     vl_logic_vector(1 downto 0);
        qp_in           : in     vl_logic_vector(6 downto 0);
        cu_req          : in     vl_logic;
        cu_done         : out    vl_logic;
        cu_depth        : in     vl_logic_vector(1 downto 0);
        cu_is_split     : in     vl_logic;
        slice_is_intra  : in     vl_logic;
        cu_skip         : in     vl_logic;
        cu_merge        : in     vl_logic;
        cu_merge_idx    : in     vl_logic_vector(2 downto 0);
        cu_pred_intra   : in     vl_logic;
        cu_part_mode    : in     vl_logic_vector(1 downto 0);
        cu_cbf          : in     vl_logic;
        cu_skip_ctx     : in     vl_logic_vector(1 downto 0);
        pred_req        : in     vl_logic;
        pred_done       : out    vl_logic;
        slice_is_b      : in     vl_logic;
        inter_dir       : in     vl_logic_vector(1 downto 0);
        ref_idx_l0      : in     vl_logic_vector(2 downto 0);
        mvp_flag_l0     : in     vl_logic;
        mvd_l0_x        : in     vl_logic_vector;
        mvd_l0_y        : in     vl_logic_vector;
        ref_idx_l1      : in     vl_logic_vector(2 downto 0);
        mvp_flag_l1     : in     vl_logic;
        mvd_l1_x        : in     vl_logic_vector;
        mvd_l1_y        : in     vl_logic_vector;
        coeff_req       : in     vl_logic;
        coeff_done      : out    vl_logic;
        coeff_comp      : in     vl_logic_vector(1 downto 0);
        coeff_is_intra  : in     vl_logic;
        coeff_flat      : in     vl_logic_vector;
        trm_req         : in     vl_logic;
        trm_bin_val     : in     vl_logic;
        flush_req       : in     vl_logic;
        flush_done      : out    vl_logic;
        byte_valid      : out    vl_logic;
        byte_out        : out    vl_logic_vector(7 downto 0);
        byte_ready      : in     vl_logic;
        enc_busy        : out    vl_logic;
        ctx_init_busy   : out    vl_logic
    );
    attribute mti_svvh_generic_type : integer;
    attribute mti_svvh_generic_type of CTX_ID_W : constant is 1;
    attribute mti_svvh_generic_type of COEFF_W : constant is 1;
    attribute mti_svvh_generic_type of MVD_W : constant is 1;
    attribute mti_svvh_generic_type of N_COEFF : constant is 1;
end cabac_enc_top;
