library verilog;
use verilog.vl_types.all;
entity hevc_encoder_top is
    port(
        clk             : in     vl_logic;
        rst_n           : in     vl_logic;
        encode_start    : in     vl_logic;
        total_frames    : in     vl_logic_vector(15 downto 0);
        encode_done     : out    vl_logic;
        in_valid        : in     vl_logic;
        in_ready        : out    vl_logic;
        in_pixel_y      : in     vl_logic_vector(9 downto 0);
        in_pixel_u      : in     vl_logic_vector(9 downto 0);
        in_pixel_v      : in     vl_logic_vector(9 downto 0);
        out_valid       : out    vl_logic;
        out_ready       : in     vl_logic;
        out_byte        : out    vl_logic_vector(7 downto 0);
        axi_awvalid     : out    vl_logic;
        axi_awready     : in     vl_logic;
        axi_awaddr      : out    vl_logic_vector(32 downto 0);
        axi_awlen       : out    vl_logic_vector(7 downto 0);
        axi_awsize      : out    vl_logic_vector(2 downto 0);
        axi_awburst     : out    vl_logic_vector(1 downto 0);
        axi_wvalid      : out    vl_logic;
        axi_wready      : in     vl_logic;
        axi_wdata       : out    vl_logic_vector(255 downto 0);
        axi_wstrb       : out    vl_logic_vector(31 downto 0);
        axi_wlast       : out    vl_logic;
        axi_bvalid      : in     vl_logic;
        axi_bready      : out    vl_logic;
        axi_arvalid     : out    vl_logic;
        axi_arready     : in     vl_logic;
        axi_araddr      : out    vl_logic_vector(32 downto 0);
        axi_arlen       : out    vl_logic_vector(7 downto 0);
        axi_arsize      : out    vl_logic_vector(2 downto 0);
        axi_arburst     : out    vl_logic_vector(1 downto 0);
        axi_rvalid      : in     vl_logic;
        axi_rready      : out    vl_logic;
        axi_rdata       : in     vl_logic_vector(255 downto 0);
        axi_rlast       : in     vl_logic
    );
end hevc_encoder_top;
