library verilog;
use verilog.vl_types.all;
entity ref_frame_buffer is
    generic(
        PIXEL_WIDTH     : integer := 10;
        BLK_SIZE        : integer := 4;
        BLK_EXT_Y       : vl_notype;
        BLK_EXT_C       : vl_notype;
        FRAME_W_Y       : integer := 3840;
        FRAME_H_Y       : integer := 2160;
        FRAME_W_C       : integer := 1920;
        FRAME_H_C       : integer := 1080;
        AXI_DW          : integer := 256;
        AXI_AW          : integer := 33;
        LUMA_SAMPLES    : vl_notype;
        CHROMA_SAMPLES  : vl_notype;
        LUMA_WORDS      : vl_notype;
        CHROMA_WORDS    : vl_notype;
        FRAME_WORDS     : vl_notype;
        CB_OFFSET       : vl_notype;
        CR_OFFSET       : vl_notype;
        SLOT_STRIDE     : vl_notype;
        PX_EXT_Y        : vl_notype;
        PX_EXT_C        : vl_notype
    );
    port(
        clk             : in     vl_logic;
        rst_n           : in     vl_logic;
        ref_req_valid   : in     vl_logic;
        ref_req_ready   : out    vl_logic;
        ref_req_comp    : in     vl_logic_vector(1 downto 0);
        ref_req_slot    : in     vl_logic_vector(2 downto 0);
        ref_req_x       : in     vl_logic_vector(11 downto 0);
        ref_req_y       : in     vl_logic_vector(11 downto 0);
        ref_resp_valid  : out    vl_logic;
        ref_resp_y_flat : out    vl_logic_vector;
        ref_resp_cb_flat: out    vl_logic_vector;
        ref_resp_cr_flat: out    vl_logic_vector;
        axi_arvalid     : out    vl_logic;
        axi_arready     : in     vl_logic;
        axi_araddr      : out    vl_logic_vector;
        axi_arlen       : out    vl_logic_vector(7 downto 0);
        axi_arsize      : out    vl_logic_vector(2 downto 0);
        axi_arburst     : out    vl_logic_vector(1 downto 0);
        axi_rvalid      : in     vl_logic;
        axi_rready      : out    vl_logic;
        axi_rdata       : in     vl_logic_vector;
        axi_rlast       : in     vl_logic
    );
    attribute mti_svvh_generic_type : integer;
    attribute mti_svvh_generic_type of PIXEL_WIDTH : constant is 1;
    attribute mti_svvh_generic_type of BLK_SIZE : constant is 1;
    attribute mti_svvh_generic_type of BLK_EXT_Y : constant is 3;
    attribute mti_svvh_generic_type of BLK_EXT_C : constant is 3;
    attribute mti_svvh_generic_type of FRAME_W_Y : constant is 1;
    attribute mti_svvh_generic_type of FRAME_H_Y : constant is 1;
    attribute mti_svvh_generic_type of FRAME_W_C : constant is 1;
    attribute mti_svvh_generic_type of FRAME_H_C : constant is 1;
    attribute mti_svvh_generic_type of AXI_DW : constant is 1;
    attribute mti_svvh_generic_type of AXI_AW : constant is 1;
    attribute mti_svvh_generic_type of LUMA_SAMPLES : constant is 3;
    attribute mti_svvh_generic_type of CHROMA_SAMPLES : constant is 3;
    attribute mti_svvh_generic_type of LUMA_WORDS : constant is 3;
    attribute mti_svvh_generic_type of CHROMA_WORDS : constant is 3;
    attribute mti_svvh_generic_type of FRAME_WORDS : constant is 3;
    attribute mti_svvh_generic_type of CB_OFFSET : constant is 3;
    attribute mti_svvh_generic_type of CR_OFFSET : constant is 3;
    attribute mti_svvh_generic_type of SLOT_STRIDE : constant is 3;
    attribute mti_svvh_generic_type of PX_EXT_Y : constant is 3;
    attribute mti_svvh_generic_type of PX_EXT_C : constant is 3;
end ref_frame_buffer;
