library verilog;
use verilog.vl_types.all;
entity input_buffer is
    generic(
        FRAME_WIDTH     : integer := 3840;
        FRAME_HEIGHT    : integer := 2160
    );
    port(
        clk             : in     vl_logic;
        rst_n           : in     vl_logic;
        wr_valid        : in     vl_logic;
        wr_ready        : out    vl_logic;
        wr_data         : in     vl_logic_vector(9 downto 0);
        wr_x            : in     vl_logic_vector(11 downto 0);
        wr_y            : in     vl_logic_vector(11 downto 0);
        wr_comp         : in     vl_logic_vector(1 downto 0);
        wr_poc          : in     vl_logic_vector(9 downto 0);
        wr_frame_last   : in     vl_logic;
        rd_req_valid    : in     vl_logic;
        rd_req_ready    : out    vl_logic;
        rd_x            : in     vl_logic_vector(11 downto 0);
        rd_y            : in     vl_logic_vector(11 downto 0);
        rd_blk_w        : in     vl_logic_vector(6 downto 0);
        rd_blk_h        : in     vl_logic_vector(6 downto 0);
        rd_comp         : in     vl_logic_vector(1 downto 0);
        rd_resp_valid   : out    vl_logic;
        rd_resp_ready   : in     vl_logic;
        rd_resp_data    : out    vl_logic_vector(9 downto 0);
        rd_resp_last    : out    vl_logic;
        axi_awvalid     : out    vl_logic;
        axi_awready     : in     vl_logic;
        axi_awaddr      : out    vl_logic_vector(32 downto 0);
        axi_awlen       : out    vl_logic_vector(7 downto 0);
        axi_awsize      : out    vl_logic_vector(2 downto 0);
        axi_awburst     : out    vl_logic_vector(1 downto 0);
        axi_wvalid      : out    vl_logic;
        axi_wready      : in     vl_logic;
        axi_wdata       : out    vl_logic_vector(31 downto 0);
        axi_wstrb       : out    vl_logic_vector(3 downto 0);
        axi_wlast       : out    vl_logic;
        axi_bvalid      : in     vl_logic;
        axi_bready      : out    vl_logic;
        axi_arvalid     : out    vl_logic;
        axi_arready     : in     vl_logic;
        axi_araddr      : out    vl_logic_vector(32 downto 0);
        axi_arlen       : out    vl_logic_vector(7 downto 0);
        axi_arsize      : out    vl_logic_vector(2 downto 0);
        axi_arburst     : out    vl_logic_vector(1 downto 0);
        axi_rvalid      : in     vl_logic;
        axi_rready      : out    vl_logic;
        axi_rdata       : in     vl_logic_vector(31 downto 0);
        axi_rlast       : in     vl_logic;
        frame_ready     : out    vl_logic;
        buffered_poc    : out    vl_logic_vector(9 downto 0);
        frame_consumed  : in     vl_logic
    );
    attribute mti_svvh_generic_type : integer;
    attribute mti_svvh_generic_type of FRAME_WIDTH : constant is 1;
    attribute mti_svvh_generic_type of FRAME_HEIGHT : constant is 1;
end input_buffer;
