library verilog;
use verilog.vl_types.all;
entity sao_top is
    port(
        clk             : in     vl_logic;
        rst_n           : in     vl_logic;
        ctu_valid       : in     vl_logic;
        ctu_ready       : out    vl_logic;
        ctu_x           : in     vl_logic_vector(9 downto 0);
        ctu_y           : in     vl_logic_vector(9 downto 0);
        sao_type        : in     vl_logic_vector(5 downto 0);
        eo_class        : in     vl_logic_vector(5 downto 0);
        eo_offset       : in     vl_logic_vector(74 downto 0);
        band_pos        : in     vl_logic_vector(14 downto 0);
        bo_offset       : in     vl_logic_vector(59 downto 0);
        pix_rd_valid    : out    vl_logic;
        pix_rd_ready    : in     vl_logic;
        pix_rd_x        : out    vl_logic_vector(5 downto 0);
        pix_rd_y        : out    vl_logic_vector(5 downto 0);
        pix_rd_comp     : out    vl_logic_vector(1 downto 0);
        pix_resp_valid  : in     vl_logic;
        pix_resp_ready  : out    vl_logic;
        pix_resp_data   : in     vl_logic_vector(9 downto 0);
        n0_rd_valid     : out    vl_logic;
        n0_rd_ready     : in     vl_logic;
        n0_rd_x         : out    vl_logic_vector(7 downto 0);
        n0_rd_y         : out    vl_logic_vector(7 downto 0);
        n0_rd_comp      : out    vl_logic_vector(1 downto 0);
        n0_resp_valid   : in     vl_logic;
        n0_resp_ready   : out    vl_logic;
        n0_resp_data    : in     vl_logic_vector(9 downto 0);
        n1_rd_valid     : out    vl_logic;
        n1_rd_ready     : in     vl_logic;
        n1_rd_x         : out    vl_logic_vector(7 downto 0);
        n1_rd_y         : out    vl_logic_vector(7 downto 0);
        n1_rd_comp      : out    vl_logic_vector(1 downto 0);
        n1_resp_valid   : in     vl_logic;
        n1_resp_ready   : out    vl_logic;
        n1_resp_data    : in     vl_logic_vector(9 downto 0);
        pix_wr_valid    : out    vl_logic;
        pix_wr_ready    : in     vl_logic;
        pix_wr_x        : out    vl_logic_vector(5 downto 0);
        pix_wr_y        : out    vl_logic_vector(5 downto 0);
        pix_wr_comp     : out    vl_logic_vector(1 downto 0);
        pix_wr_data     : out    vl_logic_vector(9 downto 0);
        ctu_done        : out    vl_logic
    );
end sao_top;
